# Generated by Django 4.2.6 on 2023-10-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalStore", "0007_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="shipping_address",
            field=models.TextField(default="N/A"),
        ),
    ]
