# Generated by Django 4.2.6 on 2023-10-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalStore", "0008_purchase_shipping_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase", old_name="shipping_address", new_name="address",
        ),
    ]
